page_size: 10
list_id: 97178021aa
tables: 
  # []
  - database: appflP5cuR8bD5MIm
    table: tbl71MaTsk6ltsa2B
    view: viwu3aTdizhuNsIkR
    tag: "ml-zoomcamp-2025"
  # - database: appzbS8Pkg9PL254a
  #   table: tblvfbVG0YFqapI4F
  #   view: viwtlnYJjNsNu1ZWS
  #   tag: "de-zoomcamp-2025"
  # - database: appYdhA23GVZd1iN2
  #   table: tblQTeFJ19T93oG7h
  #   view: viwsCXf6SxXoccjcE
  #   tag: "mlops-zoomcamp-2025"
  # - database: appPPxkgYLH06Mvbw
  #   table: tblLTQ77EtdBv98b1
  #   view: viwJZ2aaXi0YPLp3e
  #   tag: "llm-zoomcamp-2025"
  - database: appJRFiWKHBgmEt70
    table: tblLTQ77EtdBv98b1
    view: viwJZ2aaXi0YPLp3e
    tag: " ai-dev-tools-zoomcamp-2025"
